version: "3"

services:
    api:
        container_name: zipcode-search
        build: .
        command: yarn dev
        ports:
            - "3333:3333"
        volumes:
            - .:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
